# Generated by Django 4.2.4 on 2023-08-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_company_whatsapp_phone_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_whatsapp_phone',
        ),
    ]
