# Generated by Django 4.2.4 on 2023-09-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='transaction_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
