# Generated by Django 4.2.4 on 2023-08-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_whatsapp_phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
