# Generated by Django 4.2.4 on 2023-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_addcompanyamountpayment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='amount_received_paid',
            field=models.CharField(choices=[('Pending', 'Pending'), ('paid', 'paid')], default='Pending', max_length=30),
        ),
    ]
