# Generated by Django 4.2.4 on 2023-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_addcompanyamountreceived_amount_received_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcompanyamountreceived',
            name='receipt',
            field=models.ImageField(blank=True, default='receipt.png', upload_to='receipts'),
        ),
        migrations.AlterField(
            model_name='addcompanyamountreceived',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
