# Generated by Django 4.2.4 on 2023-08-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_company_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcompanyamountreceived',
            name='account_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='addcompanyamountreceived',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
