# Generated by Django 4.2.4 on 2023-09-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_addcompanyamountreceived_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount10',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount11',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount12',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount13',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount14',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount15',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount16',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount17',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount18',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount19',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount20',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount8',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='amount9',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot1',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot10',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot11',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot12',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot13',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot14',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot15',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot16',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot17',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot18',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot19',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot2',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot20',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot3',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot4',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot5',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot6',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot7',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot8',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='screenshot9',
            field=models.ImageField(default='screenshot.png', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id10',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id11',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id12',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id13',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id14',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id15',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id16',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id17',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id18',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id19',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id20',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id6',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id7',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id8',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='transaction_id9',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='addcompanyamountpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='addcompanyamountreceived',
            name='amount_received_paid',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=30),
        ),
    ]
