# Generated by Django 4.2.4 on 2023-08-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_addcompanyamountreceived_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcompanyamountpayment',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
