# Generated by Django 4.2.4 on 2023-09-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_addcompanyamountpayment_amount1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='d_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='d_10',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='d_100',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='d_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='d_20',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='d_200',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='d_5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='d_50',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
