# Generated by Django 4.2.4 on 2023-08-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_addcompanyamountpayment_company_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcompanyamountpayment',
            name='company_amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_amount', to='api.addcompanyamountreceived'),
        ),
    ]
