# Generated by Django 4.2.4 on 2023-09-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_addcompanyamountreceived_d_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='teller_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addcompanyamountreceived',
            name='teller_phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
