# Generated by Django 4.2.4 on 2023-09-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_addcompanyamountpayment_company_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcompanyamountpayment',
            name='company_amount_received',
        ),
        migrations.AddField(
            model_name='addcompanyamountpayment',
            name='company_amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_amount', to='api.addcompanyamountreceived'),
        ),
    ]
